modLoader="javafml"
loaderVersion="[35,)"

license="MIT"

[[mods]]
modId="createmore"
version="${file.jarVersion}"
displayName="Create More"
logoFile="createmore.png"
authors="guassmith"
description='''
A mod to add some extra features to Create, as well as intergrate it with other mods.
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="create"
    mandatory=true
    versionRange="[mc1.16.3_v0.3e,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="computercraft"
    mandatory=false
    versionRange="[1.95.2)"
    ordering="NONE"
    side="BOTH"